
C:\Users\emily\.texttest\tmp\ab.19Apr124348.516\ab\PublishHtmlLocker>jar tf C:\Users\emily/.texttest/tmp/ab.19Apr124348.516/ab/PublishHtmlLocker/ApprovalTests.Java/html_locker/target/HtmlLocker.jar 
META-INF/
META-INF/MANIFEST.MF
org/
org/approvaltests/
org/approvaltests/webpages/
src/
src/org/
src/org/approvaltests/
src/org/approvaltests/webpages/
org/approvaltests/webpages/WebPageApproval.class
org/approvaltests/webpages/WebPageChangeDetector.class
org/approvaltests/webpages/WebPageChangeDetectorGui.class
src/org/approvaltests/webpages/WebPageApproval.java
src/org/approvaltests/webpages/WebPageChangeDetector.java
src/org/approvaltests/webpages/WebPageChangeDetectorGui.java
